### ISSUE TITLE
systemd-resolved takes port 53 on ubuntu

### ISSUE THREAD

**Issue by russau** [mageddo/dns-proxy-server#106]
Posting this here with the hopes it will help someone else with the same issue.

On my ubuntu box starting dns-proxy-server fails with an error `udp :53: bind: address already in use`.  Port 53 has been taken by systemd-resolved, I followed the instructions here to disable it: https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

**Comment by mageddo** [comment]
@russau, thank you for your contribution
