### ISSUE TITLE
Hostname for the host machine IP

### ISSUE THREAD

**Issue by ncapilla** [mageddo/dns-proxy-server#107]
Hi,

I'm using dns-proxy-server for a docker app development. I need to resolve the host machine IP by hostname. I know how to achieve it using host.docker, but I'm using a connector that I can't modify which is using my hostname.

So, is there any way to resolve my hostname to 127.0.1.1? Linking the dns proxy server to /etc/hosts or something like that.

Maybe it can be already achieved, but I can't do it reading the docs, http://mageddo.github.io/dns-proxy-server/ :S

Thanks!!

**Comment by mageddo** [comment]
@ncapilla Not sure if you already tried and didn't achieve your objective but DPS have a local storage where you can create hostname entries (A DNS records)

You can access the GUI by http://localhost:5380 or http://dns.mageddo, configure a new hostname that solves to 127.0.1.1 then you're done.

The GUI will create a new hostname entry at the config.json [see this page](http://mageddo.github.io/dns-proxy-server/docs/running.html#configure-your-dns)

**Comment by mageddo** [comment]
The issue here is that Linux solve hostnames looking at /etc/hosts before, then it try to solve using DNS server, so if you have some entry on your hosts file with machine hostname then DPS resolution will be discarded


Consider temporarily comment them

**Comment by ncapilla** [comment]
When I execute "nslookup $HOSTNAME" it resolve to 127.0.1.1, but once dns-proxy-server started it stops resolving my hostname. And it should use the /etc/hosts file first...

I'm missing something, I'll check out my ubuntu config.

**Comment by ncapilla** [comment]
Is it possible to ask the local dns server after trying the other ones?

As your documentation points out, first it finds a match at docker containers, second at local db, then it try to look at 8.8.8.8. What about a final step asking to local dns server?

**Comment by mageddo** [comment]
> Is it possible to ask the local dns server after trying the other ones?

A local entry inside your config.json will not work cause DPS is running inside docker container, it can't listen to local DNS server

You can define multiple nameservers at your /etc/resolv.conf 

> If I comment the line "nameserver 127.0.0.53" in the /etc/resolv.conf file, then "nslookup $HOSTNAME" stops resolving localhost. So when I start dns-proxy-server and this line get commented it also stop working.

This sound very strange for me, I thought resolv.conf wasn't necessary to solve hosts file hostnames.

> Adding my hostname to the config.json is a valid workaround for my local machine. But I'm running this setup on multiple environment so I need to do it dinamically :s

I see, I think make host machine hostname be configurable is not a big change, I will consider develop it in the next days

**Comment by ncapilla** [comment]
I finally found the error, the connector is listening on a port in the host machine. Then a container is trying to open a connection to the host machine using its hostname.
So, It isn't a problem with the dns-proxy-server...

Anyway making host machine hostname configurable is a nice feature to consider ;)

Thanks for your help!!

**Comment by mageddo** [comment]
Feature was developed, please check the [release notes](https://github.com/mageddo/dns-proxy-server/releases/tag/2.11.0).

Be aware if you set the host machine hostname as the machine name then you will have to remove
it's name from `/etc/hosts` since OS try to resolve names from hosts file first
then from DNS server

**Comment by mageddo** [comment]
Feel free to comment if you wish to discuss about anything related to this issue
