### ISSUE TITLE
Fix for slow ping regressed in >= 2.14.0 

### ISSUE THREAD

**Issue by russau** [mageddo/dns-proxy-server#139]
Hello,

Thank you for creating this tool, I'm finding it very useful for some training environments that I create.

I think the fix for #119 has regressed in version 2.14.0.  Ping is very fast for me in 2.13.2, but is now slow in version 2.14.0.  I have a similar situation to the original ticket: I'm attempting to ping `container1` and my `/etc/resolv.conf` contains a `search hsd1.wa.comcast.net`.

Let me know if you would like me to provide any more logs or details.

Thanks again!

**Comment by mageddo** [comment]
Do you still have this issue at 2.1.4.5?

**Comment by russau** [comment]
Yes, I was updating some scripts to run the most recent version when I first noticed the problem.

**Comment by mageddo** [comment]
Okay, I'll try to simulate the issue, I think we really need some automated tests for this

**Comment by mageddo** [comment]
Issue was fixed on **2.14.6** can you confirm?

**Comment by russau** [comment]
I tested with https://github.com/mageddo/dns-proxy-server/releases/download/2.14.6/dns-proxy-server-linux-amd64-2.14.6.tgz - all looks good!
