### ISSUE TITLE
host.docker can't resolved

### ISSUE THREAD

**Issue by jwundrak** [mageddo/dns-proxy-server#159]
### What is expected

From the linux-Teams: resolving host.docker is not work anymore since 2.14.6

### What is Happening

Resolving host.docker returns an not found

**Specs:**
- OS: (K)ubuntu/arch
- Docker Version: min 18.03
- DPS Version: latest hub_version

**Comment by mageddo** [comment]
I've tried and it works well for me, can you elaborate the steps to reproduce the issue?

```
$ docker run --rm --hostname dns.mageddo \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/resolv.conf:/etc/resolv.conf \
defreitas/dns-proxy-server:2.18.0

$ nslookup host.docker
Server:		172.17.0.2
Address:	172.17.0.2#53

Non-authoritative answer:
Name:	host.docker
Address: 172.17.0.2
Name:	host.docker
Address: 172.17.0.2

```

**Comment by mageddo** [comment]
@jwundrak
