### ISSUE TITLE
HOSTNAMES env not fully respected

### ISSUE THREAD

**Issue by lupujo** [mageddo/dns-proxy-server#164]
### What is Happening

When using the HOSTNAMES env, those are properly resolved by the docker host (when using in /etc/resolv.conf the dns docker IP address) but not by the docker containers (when using in /etc/resolv.conf the 127.0.0.11 IP address)

### What is expected

Resolving should be the same from outside and from inside the docker container.

### Steps to Reproduce

1. Set HOSTNAMES for a docker container.
2. Try to resolve from docker host - works.
3. Try to resolve from any docker container - does not work.

**Comment by mageddo** [comment]
Hello @lupujo, thanks for the report.

I couldn't reproduce your issue, I think it really depends how you're starting DPS and your containers, can you please provide a full example?

Starting DPS
```bash
docker run --rm --hostname dns.mageddo \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/resolv.conf:/etc/resolv.conf \
defreitas/dns-proxy-server
```

Starting my testing container
```bash
docker run -e HOSTNAMES=nginx1.intranet --rm --name nginx-1 nginx
```

Starting and testing `HOSTNAMES` hosts from another container
```
docker run --name linux-1 --rm -it alpine sh -c 'apk add --update curl iputils bind-tools; sh'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
....
/ # nslookup nginx1.intranet
Server:		172.17.0.2
Address:	172.17.0.2#53

Non-authoritative answer:
Name:	nginx1.intranet
Address: 172.17.0.3
Name:	nginx1.intranet
Address: 172.17.0.3
```

DPS version: 2.18.0

Best regards
