### ISSUE TITLE
Container can't restart if config.json file is maintained

### ISSUE THREAD

**Issue by imartinezortiz** [mageddo/dns-proxy-server#165]
### What is Happening

* Describe what is happening instead

Container can't restart (or a new one created) if the conf/config.json sets LogLevel parameter, the config file is reused between restarts (e.g. bind mount) and the config file is changed during runtime, for example, by adding a DNS entry (DPS writes the config file). 

Seems that https://github.com/mageddo/dns-proxy-server/commit/e380797f3eb3560e5b41b3e08e12e63c41c23d22 introduced the bug,
```
func ValueOf(c *localvo.Configuration) *ConfigurationV2 {
	return &ConfigurationV2{
		Version:                int64(2),
		LogFile:                c.LogFile,
		ActiveEnv:              c.ActiveEnv,
		DefaultDns:             c.DefaultDns,
		DnsServerPort:          c.DnsServerPort,
		Domain:                 c.Domain,
		HostMachineHostname:    c.HostMachineHostname,
		**LogLevel:               c.LogFile,**
```
### What is expected

The container should restart without issues or a new container could be created reusing the config file.

### Steps to Reproduce
```
cat << EOF > config.json
{
        "version": 2,
        "remoteDnsServers": [],
        "envs": [
                {
                        "name": ""
                }
        ],
        "activeEnv": "",
        "webServerPort": 0,
        "dnsServerPort": 0,
        "defaultDns": null,
        "logLevel": "DEBUG",
        "logFile": "console",
        "registerContainerNames": null,
        "hostMachineHostname": "",
        "domain": "",
        "dpsNetwork": false,
        "dpsNetworkAutoConnect": false
}
EOF

docker run --name dps -v $PWD/config.json:/app/conf/config.json -d -p 5390:5380 defreitas/dns-proxy-server:2.18.1

# Add a DNS entry using the UI

docker stop dps

docker start dps

# container Exited

docker logs dps &> dps.log
docker cp dps:/app/conf/config.json config-wrong.json.txt

```

[dps.log](https://github.com/mageddo/dns-proxy-server/files/3743438/dps.log)
[config-wrong.json.txt](https://github.com/mageddo/dns-proxy-server/files/3743440/config-wrong.json.txt)

**Specs:**
- OS: Ubuntu 16.04.2
- Docker Version: 19.03.3
- DPS Version: 2.18.1
- Please attach DPS Log file

**Comment by mageddo** [comment]
@imartinezortiz thanks for the contribution, it appears the bug is [at this point](https://github.com/mageddo/dns-proxy-server/commit/e380797f3eb3560e5b41b3e08e12e63c41c23d22#diff-d458d7f6dd9cd9153f56ec0aa76be254R57)

Fixing on #168

**Comment by mageddo** [comment]
Please re open if don't work for you

**Comment by imartinezortiz** [comment]
Thanks !, I can confirm that 2.18.2 docker image fix the problem.
