### ISSUE TITLE
Getting backtraces when remote DNS servers replies with NXDOMAIN

### ISSUE THREAD

**Issue by selurvedu** [mageddo/dns-proxy-server#172]
### What is Happening

* NXDOMAIN answer from a remote DNS server produces a stack trace on INFO log level
* DPS itself does not return an NXDOMAIN answer, `nslookup` reports "No answer" instead
* See the log file for a backtrace: [dps-issue-172.log](https://github.com/mageddo/dns-proxy-server/files/3974182/dps-issue-172.log)

### What is expected

* The backtrace should not appear in logs (at least on INFO log level)
* DPS should forward the NXDOMAIN answer of the remote DNS server

### Steps to Reproduce

172.20.0.2 is the IP address of DPS

```
$ nslookup asdasdsadasdas.com 9.9.9.9
Server:         9.9.9.9
Address:        9.9.9.9#53

** server can't find asdasdsadasdas.com: NXDOMAIN

$ nslookup asdasdsadasdas.com 172.20.0.2
Server:         172.20.0.2
Address:        172.20.0.2#53

Non-authoritative answer:
*** Can't find asdasdsadasdas.com: No answer
```

**Specs:**
- OS: The official image of DPS on Docker Hub uses Debian GNU/Linux 10 (buster)
- Docker Version: 19.03.4-ce
- DPS Version: 2.18.2

**Comment by mageddo** [comment]
Yep, I confirmed it today, not sure yet what caused, it is generating a LOT of stacktraces. Thanks for the report @selurvedu
