### ISSUE TITLE
Resolving host IP address without DPS network

### ISSUE THREAD

**Issue by mrubli** [mageddo/dns-proxy-server#183]
This is part question, part feature request, and part offer to help. 😉

It appears that `host.docker` always resolves to the DPS container's IP address instead of the host machine IP unless the DPS network is enabled. I've observed this on two systems and glancing at the code seems to confirm my suspicion because the gateway IP address is only obtained if the DPS network is active.

Maybe there are some scenarios I'm not thinking of right now but falling back to e.g. the `bridge` network and obtaining its gateway should give an IP address that's routable from most Docker networks. If this is not true for the general case perhaps a "try harder to find the host IP address" or "use network X's gateway as the host IP address" a command line switch would be useful, so that users can enable it in cases where it does work.

Any thoughts? I'd be happy to help out with the implementation if this sounds useful. (It certainly would be for me cause that's pretty much the only thing missing right now in my personal use cases.)

**Comment by mageddo** [comment]
> It appears that host.docker always resolves to the DPS container's IP address instead of the host machine IP unless the DPS network is enabled. 

> Maybe there are some scenarios I'm not thinking of right now but falling back to e.g. the `bridge`

I think it makes sense

> use network X's gateway as the host IP address
Yep, it can be used as fallback if bridge network don't exists for some reason, I'm getting the first network listed

I've implemented these behaviors

**Comment by mageddo** [comment]
Fixed, please make a mention if you have some issue. 

Regards

**Comment by mrubli** [comment]
After some initial testing everything looks great and works as expected. Thanks a lot for implementing that so soon! 👍
