### ISSUE TITLE
conf-path opens a nonexistent file

### ISSUE THREAD

**Issue by 9yx** [mageddo/dns-proxy-server#188]
### What is Happening

Start dps with `-conf-path=/etc/dns-proxy-server/config.json`, (dps location `/usr/bin/dns-proxy-server`)

when start dps open config `/usr/bin/etc/dns-proxy-server/config.json`

### What is expected

Open config `/etc/dns-proxy-server/config.json`

### Steps to Reproduce

Start:
```bash
/usr/bin/dns-proxy-server -conf-path=/etc/dns-proxy-server/config.json
```

**Specs:**
- OS: Archlinux
- Docker Version: 19.03.5-ce
- DPS Version: 2.18.7

```bash
$ /usr/bin/dns-proxy-server -conf-path=/etc/dns-proxy-server/config.json
2020/01/13 13:02:16.003274 ERROR f=local.go:123 pkg=github.com/mageddo/dns-proxy-server/events/local m=storeDefaultConfig status=error-to-create-conf-path, path=/usr/bin/etc/dns-proxy-server/config.json
2020/01/13 13:02:16.003354 ERROR f=local.go:123 pkg=github.com/mageddo/dns-proxy-server/events/local m=storeDefaultConfig status=error-to-create-conf-path, path=/usr/bin/etc/dns-proxy-server/config.json
```

**Comment by mageddo** [comment]
Looks like `-conf-path` feature wasn't designed to support absolute paths, I think it makes sense to support it.

https://github.com/mageddo/dns-proxy-server/blob/632d36a46a20230632b2b8dc38524dda7678fc13/utils/utils.go#L168-L177
