### ISSUE TITLE
Change the IP address that the dns-proxy-server operates on.

### ISSUE THREAD

**Issue by trapeze-bell-peter** [mageddo/dns-proxy-server#192]
I have posted this also as a question on [Stackflow](https://stackoverflow.com/questions/60839978/how-to-configure-dns-proxy-server-in-docker-compose-to-bind-to-a-non-default-ip).

I am using mageddo/dns-proxy-server in my RoR environment to provide DNS resolution for the docker containers. This works like a treat until I connect to the company VPN. Unfortunately, dns-proxy-server binds to the port 172.17.0.2 which conflicts with the VPN. My other containers are using a different IP range.

I am wondering whether there is a way to get dns-proxy-server to bind to a different IP address to avoid the conflict with the VPN.

Many thanks in advance.

**Comment by mageddo** [comment]
@trapeze-bell-peter you can specify DPS container IP on the start, [see][1]

[1]: https://github.com/mageddo/dns-proxy-server/blob/f6371b/examples/custom-hostnames-compose-file/docker-compose.yml#L13

**Comment by mageddo** [comment]
Not sure if my answer helped, feel free to continue the discussion if need it

**Comment by trapeze-bell-peter** [comment]
Really sorry.  I thought I had answered.  Your answer was perfect!
