### ISSUE TITLE
Access from Another System

### ISSUE THREAD

**Issue by jasi110** [mageddo/dns-proxy-server#206]
I have a docker-compose.yml of SolrCloud - three zookeeper containers, and three solr containers.  CloudSolrClient allows a connection using the zookeeper hosts and ports, and that is what I am looking to do with DPS.  I have DPS running with register container names and I can nslookup and ping the zookeeper containers: zoo1.docker, zoo2.docker, and zoo3.docker.  All of this is great.  Now, the product that calls into the SolrCloud is on another host.  From that host, I try to issue "ping zoo1.docker" and that fails with a host not found.
Is there a way to make zoo1.docker available to other systems on the host network?
Thank you for any assistance.

**Comment by mageddo** [comment]
Giving more details, about @polarathene answer, I will consider

> I have a docker-compose.yml of SolrCloud - three zookeeper containers, and three solr containers. CloudSolrClient 
as Machine 1

> Now, the product that calls into the SolrCloud is on another host. 
As Machine 2

In your cause you can have two different solutions:

1 - Configure  Machine 2 to use Machine 1 IP as the DNS Server as DPS is running on that.
2 - Also runs DPS on Machine and configure local entries to point `zoo1.docker` to Machine 1 IP

In both case you will need to publish the containers ports.

Or 3, a better solution would be to use docker swarm or kubernetes manage the machine cluster to you.

Closing the issue, if you have any doubt please re-open it.
