### ISSUE TITLE
Use in combination with Adguard?

### ISSUE THREAD

**Issue by royduin** [mageddo/dns-proxy-server#214]
Adguard needs port 53 but systemd-resolved is running which DPS needs, is it possible to run it together?

**Comment by mageddo** [comment]
It's now possible, check on DPS 3.5.2, DPS will use systemd-resolved when available, DPS will need to start using port 53 but will bind to an different IP.

It's a missing feature  to configure DPS at system-resolved with a custom por instead of fixed 53

**Comment by mageddo** [comment]
> configure DPS at system-resolved with a custom por instead of fixed 53

Is now possible as DPS 3.6
