### ISSUE TITLE
Cannot add CNAME record in the web UI: Invalid JSON

### ISSUE THREAD

**Issue by ulidtko** [mageddo/dns-proxy-server#219]
The web UI generates an error 400 when trying to add a CNAME record:

![image](https://user-images.githubusercontent.com/365338/113138150-139ae000-922e-11eb-9e83-c5f1e8fb7b40.png)

It seems that the backend has troubles parsing the resulting HTTP request:
> Invalid JSON: json: cannot unmarshal string into Go struct field HostnameV1.ip of type [4]uint8

### What is expected

CNAME record added.

### Steps to Reproduce

 * Create and select a custom Environment on the `:5380` web UI.
 * Try to add a CNAME record

- DPS Version: `2.19.0`

**Comment by uvaa** [comment]
some tips to create cname record

1.  do not select the `Type` on `CNAME` ( default it's `A` )
2.  input your `Hostname`
3.  input any text in `IP` ( just in case the IP is empty )
4.  select the `Type` to `CNAME`, then input your `Target` and save data

**Comment by PriamX** [comment]
Same issue here.

Above tip didn't work, however, gave a different error: "×env not found"

**Comment by mageddo** [comment]
I got some related behavior, but fixed it at `3.5.2`  can you try it? 

@PriamX / @uvaa / @ulidtko

**Comment by mageddo** [comment]
I'm closing this but feel free to reopen if the issue persists

**Comment by PriamX** [comment]
@mageddo Tested with docker defreitas/dns-proxy-server 3.7.0...it works now! Thank you.
