### ISSUE TITLE
Does dns-proxy-server support network-scoped aliases for a container?

### ISSUE THREAD

**Issue by groall** [mageddo/dns-proxy-server#234]
### What is expected

Doed dns-proxy-server support network-scoped aliases for the container?

### What is Happening

I use aliases to connect containers to each other by a domain like in production. It works with a proxy server for http requests from a host or with coredns for other type request. But using coredns has the problem: from time to time a host OS doesnt use it due to rewriting resolf.conf. DPS overwrites resolv.conf and I would be like to use it instead of coredns to access containers by alias.

**Comment by mageddo** [comment]
> But using coredns has the problem: from time to time a host OS doesnt use it due to rewriting resolf.conf. 

If your Linux has systemd-resolved installed then this issue will be resolved, try DPS 3.5.2, see #321

**Comment by mageddo** [comment]
Closing this issue, feel free to reopen it when you are able to respond
