### ISSUE TITLE
How to pass JSON config running mageddo.dns with `docker run`?

### ISSUE THREAD

**Issue by Felix-neko** [mageddo/dns-proxy-server#236]
Hi folks! And thank you for your project, it's really helpful.

I have just one question: how can I pass some JSON config to DNS when I run it with `docker run` ?

**Comment by mageddo** [comment]
Something like that

```
docker run -v $PWD/config/:/app/conf/ defreitas/dns-proxy-server
```

See [docker-compose example][1]

[1]: https://github.com/mageddo/dns-proxy-server/tree/master/examples/pre-registered-hosts
