### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by crkinard** [mageddo/dns-proxy-server#241]
### What is Happening

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error

### What is expected

Successful install

### Describe which steps should be followed to reproduce the issue

docker run --rm --hostname dns.mageddo \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/resolv.conf:/etc/resolv.conf \
defreitas/dns-proxy-server

### Specs
Raspberry Pi 3b+
Linux rbpi-00 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
Docker version 20.10.5+dfsg1, build 55c4c88

**Comment by mageddo** [comment]
The default image is a linux amd64 then that's why you're getting this error as raspberry PI runs on top of an arm processor.

Give a look at the arm images available https://hub.docker.com/r/defreitas/dns-proxy-server/tags?page=1&name=aarc
