### ISSUE TITLE
DPS regularly crashes

### ISSUE THREAD

**Issue by hydrargyrum** [mageddo/dns-proxy-server#247]
### What is Happening

* DPS is running
* For some reason, a container is missing (don't ask me why, I don't know)
* DPS crashes, with this kind of log:

```
dns_1  | panic: status=inspect-error, id=167fc425daa487eaa5702fb0c9a8ab5ee9fffc5ed0a3258c08cfcfeadf8b0799: Error: No such container: 167fc425daa487eaa5702fb0c9a8ab5ee9fffc5ed0a3258c08cfcfeadf8b0799
dns_1  |
dns_1  | goroutine 7 [running]:
dns_1  | github.com/mageddo/dns-proxy-server/events/docker.mustInspectContainer(0x8fede0, 0xc00019bc50, 0xc0004c84c0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
dns_1  |        /app/src/github.com/mageddo/dns-proxy-server/events/docker/docker.go:116 +0x24b
dns_1  | github.com/mageddo/dns-proxy-server/events/docker.HandleDockerEvents()
dns_1  |        /app/src/github.com/mageddo/dns-proxy-server/events/docker/docker.go:101 +0x1069
dns_1  | created by main.main
dns_1  |        /app/src/github.com/mageddo/dns-proxy-server/dns.go:126 +0xe6
```

### What is expected

DPS should not crash in case of "missing container", the missing one should simply be ignored.

### Steps to Reproduce

**Specs:**

-    OS: Debian stable
-    Docker Version: 20.10.5+dfsg1
-    DPS Version: 2.19.0

**Comment by mageddo** [comment]
Hey, it probably is related to some concurrency scenario, difficult to reproduce. DPS 3 makes sure which any solver failure can't break the whole thing, take a look at that, it's in beta version though, I'm using it on my machine to stress  out the use cases, I think it's pretty stable for a beta :D . Give it a try if you're still using DPS and give me the feedback if possible.

Thanks.
