### ISSUE TITLE
systemd-resolved integration

### ISSUE THREAD

**Issue by sh3bang** [mageddo/dns-proxy-server#248]
Hello,

first of all: DPS is a very helpful Service, thank you very much!

I can understand to replace the /etc/resolv.conf file, it is the most common way to use a different DNS Server. But with systemd-resolved on the Host it isn't recommend. systemd-resolved offer a API to change or add DNS Servers. Therefore i ask to integrate systemd-resolved instead of replacing system files.

**Comment by SimJoSt** [comment]
Duplicate: https://github.com/mageddo/dns-proxy-server/issues/246

**Comment by mageddo** [comment]
Hey, thank your for the feedback @sh3bang .

I wouldn't know about this systemd-resolved ability to change the DNS servers, I think it would be a nice feature, I will take a look to understand how to use it, probably won't be a problem when running locally but asking myself if it will be possible to use that when DPS is running inside a container.

**Comment by sh3bang** [comment]
The mistake is to replace /etc/resolv.conf by DPS Container. Keep it as-is and add a custom DNS server (DPS on top of all other in the resolver list), e.g. by adding the container IP to /etc/systemd/resolved.conf
Or just have a look at "adguard"

**Comment by mageddo** [comment]
Hey @sh3bang I've made some tests with systemd-resolved and reported them [on this thread][1], when using it correctly docker behavior gets a lot better, but I've noticed that won't to able to automatically configure system-resolved when DPS is running inside a container as I expected because systemd-resolved restart is required.

Do you know any workaround?


[1]: https://github.com/mageddo/dns-proxy-server/issues/244#issuecomment-1445179978

**Comment by mageddo** [comment]
Contents about sending commands from container to the host:

* https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container
* https://stackoverflow.com/questions/24750137/restarting-host-from-docker-container

**Comment by mageddo** [comment]
I consolidate the feature specs at https://github.com/mageddo/dns-proxy-server/issues/321

**Comment by mageddo** [comment]
The feature is alive at DPS 3.4, please check it out and give me a feedback if possible. See #321 for some instructions of how to use it, I will update the docs later.

I'm using the following command:

```bash
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/systemd/:/host/etc/systemd --network host \
defreitas/dns-proxy-server:3.4.0-beta
```

**Comment by sh3bang** [comment]
@mageddo Thanks, DPSis now working fine with systemd-resolved!
