### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by markonsn** [mageddo/dns-proxy-server#27]
I have a docker container whith nginx and wordpress and use dns-proxy-server to resolve this as testdomain.dev.

I have configured nginx: 

```
server {
    listen       80;
    server_name  *.testdomain.dev;
    ...
}
```
and try this too:
```
    listen       80  default_server;
```
How can I configure to use *.testdomain.dev?

**Comment by mageddo** [comment]
Hy @markonsn.

If I understand your point, at NGINX you want to proxy all traffic of all **testdomain** subdomains, is that right?

Now, I am no sure what are you not able to do with **dns proxy server**, if it is to solve all subdomains to the same container I am afraid that is not possible yet. 

What you can do today is to start a container with many domains attached to, eg:

```bash
$ docker run --rm -e HOSTNAMES=server1.testdomain.dev,server2.testdomain.dev nginx
```

Then let me ask why solve all subdomains to a container is a good thing to you? Are you using Wordpress multiple sites or something like that?

Regards.

**Comment by mageddo** [comment]
I Will close, if you have any update please re-open it
