### ISSUE TITLE
Resolution of `host.docker` goes to the container hosting DPS, rather than the host.

### ISSUE THREAD

**Issue by lflare** [mageddo/dns-proxy-server#384]
As also mentioned in #380, I recently noticed that a few production applications I have suddenly stopped being able to connect to my database, which is hosted on the host's network stack. This configuration was done through simply specifying `host.docker` in the configuration fields, and I had no issue with it up till 3.13.1.

However just today, as I have most of my containers on auto-update for the most parts, including DPS, when DPS updated to 3.14, I noticed that `host.docker` stopped resolving to `172.18.0.1`, and instead started resolving to `172.18.0.254`, which was the IP address of the DPS container. I understand that the resolution of `host.docker` might have changed, but perhaps it would be great to specify this as a potentially breaking change?

**Comment by mageddo** [comment]
Hey @lflare , it isn't a breaking change, it's a bug, sorry for that, the #380  was supposed to do a better ensure of the feature behavior a someway it broke your use case.

You are running DPS on a container, right?

**Comment by mageddo** [comment]
I wouldn't recommend you to use the `latest` tag on environments anyway, DPS latest tag is used for the very recent versions including pre-releases. Use `latest` version is also considered a bad practice as it won't guarantee [reproducible builds][1].

I'm working on the fix right now.

[1]: https://en.wikipedia.org/wiki/Reproducible_builds

**Comment by mageddo** [comment]
> However just today, as I have most of my containers on auto-update for the most parts, including DPS...

Are you using the latest tag? I wouldn't recommend you to use the `latest` tag on environments or "auto update" the container to the latest version automatically, DPS latest tag is used for the very recent versions including pre-releases. 

It would be better before upgrade to test your usecases then release it to your prod env. See a bit more information at [Reproducible builds][1].

I intend to respect major, minor and minor releasing but bugs are an unexpected behavior.

[1]: https://en.wikipedia.org/wiki/Reproducible_builds

**Comment by mageddo** [comment]
3.14.4 is out, it fixes the this issue, can you try it?

**Comment by lflare** [comment]
The issue seems to have been resolved. Thanks for the quick turnaround.

With regards to the stability and reproducibility of builds, perhaps there can be some kind of `production` tag, or perhaps having a `nightly`/`unstable` tag instead? I think Docker defaults to the `latest` tag when it comes to pulling or running an image, so perhaps it might be better releasing new versions under a different tag, `unstable` or `nightly`, letting it get enough traction and bug stomping before re-releasing it under the `latest` tag?

**Comment by mageddo** [comment]
> The issue seems to have been resolved. Thanks for the quick turnaround.

That's good news.

> With regards to the stability and reproducibility of build...

Sounds like a good idea, I will change the latest to latest stable version and create a `nightly` tag.
