### ISSUE TITLE
Plan from migrating away from dockerhub?

### ISSUE THREAD

**Issue by hydrargyrum** [mageddo/dns-proxy-server#391]
DPS's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/) ([see also](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)). Do you have any plans for migrating hosting elsewhere?

**Comment by mageddo** [comment]
Hey,  for this whole thing what I get more worried about was the 200 pulls limit every 6 hours, or even worse 100 pulls for unauthenticated users. This limit can be easily met if the client is using DPS on some infra structure solution.

Despite that I haven't any complains about that, you is the first one to touch in that subject. I think the best alternative will be Github packages, any other suggestions? 

I haven't plans to migrate it right now, if people start giving feedback which are having a bad experience on Docker Hub then I would start to publish the image to two places and deprecated Docker Hub at some point.

References

* [Docker Pricing][1]
* [Github packages pricing (free and unlimited for opensource projects][2]

[1]: https://user-images.githubusercontent.com/5281356/226793363-29652c12-c04c-4de0-870a-9379eb57d548.png
[2]: https://github.com/features/packages#pricing

**Comment by hydrargyrum** [comment]
Yes, I think you can have both dockerhub (as long as it works) and GHCR.
