### ISSUE TITLE
Documentation: registerContainerNames feature still unclear

### ISSUE THREAD

**Issue by wget** [mageddo/dns-proxy-server#417]
### What is expected

Be registerContainerNames enabled or not, this doesn't change anything in my configuration.

Hence the fact I tried to dig into the documentation, but the latter is not really meaningful about the purpose of this feature.

Digging into the code was not meaningful either.

Do you have a simple use case which could explain the purpose of this feature? If understandable enough, we could add it to the docs.

### What is Happening

What is the actual behavior and lacks without this feature and what's the fallback while this feature is not implemented yet

### Changes (Optional)

Providing an example in the doc would be more meaningful.

**Comment by mageddo** [comment]
Have you checked [this doc](https://mageddo.github.io/dns-proxy-server/latest/en/2-features/accessing-container-by-name/) ?

**Comment by mageddo** [comment]
Feel free to reopen the issue when able to respond it.
