### ISSUE TITLE
Dockerhub tags of stable releases

### ISSUE THREAD

**Issue by pschiffe** [mageddo/dns-proxy-server#569]
Hi @mageddo, I have a quick question regarding the docker image tags on the Docker Hub. For snapshot / development releases I see the following tags:
```
3.30.0-snapshot
3.30.0-snapshot-amd64-static
3.30.0-snapshot-aarch64
```

However, for the stable release, I see:
```
latest
3.25.10-aarch64
3.25.10-amd64-static
```

Is the `latest` the non-static `amd64` version? Could it be tagged as `3.25.10-amd64` or `3.25.10` as well, so it could be pinned?

I'm currently on the `snapshot` variant, but I would like to migrate to the stable releases. Also, for the production use as Docker container, what's better? `amd64` or `amd64-static`?

**Comment by mageddo** [comment]
Hey, @pschiffe 

> Is the latest the non-static amd64 version? Could it be tagged as 3.25.10-amd64 or 3.25.10 as well, so it could be pinned?

Yes, for all the questions. I will make an adjust so new latest images will be generated as "3.25.10" respecting the pattern used in the snapshot version.



> I'm currently on the snapshot variant, but I would like to migrate to the stable releases. Also, for the production use as Docker container, what's better? amd64 or amd64-static?

I consider the static image is more convenient as it's based on the scratch docker image, so it's lighter, despite on this, there is no difference.

Use the static binary is good for compatibility but when using docker containers that's not a point. 
>  A statically linked binary has all of the required library code built in, so it's big (wastes disk space) but will run on just about any system of the same type it was compiled on. If the binary is dynamically linked (uses shared libraries), all systems it is to run on must have a copy of all the required libraries. [1][1]


[1]: https://www.linuxquestions.org/questions/linux-general-1/binary-static-or-dynamic-414271/

**Comment by mageddo** [comment]
[release-latest.yml.txt](https://github.com/user-attachments/files/16994354/release-latest.yml.txt)

**Comment by pschiffe** [comment]
Awesome, thank you.

When you feel like it, you could consider multiarch images as well, where 1 tag on docker hub contains more than one arch. Such as here, for example: https://hub.docker.com/_/debian/tags
More info: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by mageddo** [comment]
The pull request was created, next latest release will be generated right after September 30 including the new tags

**Comment by mageddo** [comment]
A specific tag was generated to amd64 on the new latest image, [see it][1].

I'm planning #584  to support multiarch on the generated snapshots and latest images.

Please reopen if you have any adjustment to be done related to this task, thanks in advance 🙏 .


[1]: https://hub.docker.com/layers/defreitas/dns-proxy-server/3.25.11/images/sha256-00f9c831e8d2a04ae5b3df2e21fda6db2feb1384f1bc6f4f11fbb17881c86174?context=repo
