### ISSUE TITLE
DPS Lose DNS server configuration after system unsuspension, or network configuration

### ISSUE THREAD

**Issue by mageddo** [mageddo/dns-proxy-server#62]
Using `-default-dns` DPS will be settled as default Linux DNS. If you suspend linux DPS will not be the default DNS server after unsuspend. It also happen sometimes if you unplug and plug network cable or wifi.

**Comment by fezfez** [comment]
@mageddo : same for me, i have to stop and start the service when a lost wifi

**Comment by mageddo** [comment]
I think DPS will have to monitor host machine  DNS configurations while it is running

**Comment by mageddo** [comment]
@fezfez Fixed at `2.5.4` DPS will monitor resolvconf and update that every 20 seconds if necessary

**Comment by fezfez** [comment]
@mageddo : thanks for your awesome work !
