### ISSUE TITLE
dns resolve during image build

### ISSUE THREAD

**Issue by johnbritto1** [mageddo/dns-proxy-server#63]
[dns-proxy-log.txt](https://github.com/mageddo/dns-proxy-server/files/1870499/dns-proxy-log.txt)
Hi,

I am using docker eclipse tooling to connect with the remote docker instance using TLS.
The docker build RUN could not resolve dns for command "apt-get install package".
Here is the error shown by dns-proxy-server

[36m18-04-03 06:42:00.016 DEB [0mid=53, m=handleQuestion status=not-resolved, solver=proxy.DockerDnsSolver, err=hostname not found opqobwuqbukhds
[36m18-04-03 06:42:00.016 DEB [0mid=54, m=handleQuestion status=not-resolved, solver=proxy.DockerDnsSolver, err=hostname not found jqwjuxddshtl

Any workaround.  If I stop the dns-proxy-server, docker build could resolve the DNS. 

I have attached the complete log.

Thanks.

**Comment by mageddo** [comment]
@johnbritto1 Sorry for the too late answer

1. Which package are you trying to install? 
2. Other command like `apt-get update` works great?
3. Are you using DPS at your local machine or at the remote server?

**opqobwuqbukhds** sounds like a local hostname, I don't think it's related to apt-get. I saw the only one debian server question was successfully answered

```
[36m18-04-02 15:34:21.039 DEB [0mid=19, m=handleQuestion status=resolved, solver=*proxy.remoteDnsSolver, alength=5, answer=deb.debian.org.	3599	IN	CNAME	static.debian.org.
```

You could try add a custom DNS server (you can get some taking a look at `/etc/resolv.conf`) at config file `/opt/dns-proxy-server/conf/config.json`

```javascript
{
    "remoteDnsServers": [[0,0,0,0]]
}

Regards

**Comment by johnbritto1** [comment]
Hello Mageddo,
Thanks for reply.

To answer you questions.
1. The build script could not pass after running apt-get update.
2. I use DPS on remote server.

After adding the dns-server entry in /etc/docker/daemon.json file..

"dns": ["8.8.8.8", "8.8.4.4"],

the issue resolved.

Thanks,
John

**Comment by mageddo** [comment]
Thanks for sharing the solution, it would be helpful in the future

**Comment by Luca8991** [comment]
I'm also had this problem after setting up the **dns-proxy-server**.
@mageddo do you have any idea of what's causing it?
