### ISSUE TITLE
Update documentation: How to use on Windows

### ISSUE THREAD

**Issue by imjosh** [mageddo/dns-proxy-server#66]
I wanted to use this on Windows 10 as an alternative to editing my HOSTS file.  I was able to get this working using Docker CE for Windows w/ Linux containers, but I had to use this `docker run` command to get it to work (it took me about an hour to figure this out).   The only other thing I had to do was change my network adapter setting by making 127.0.0.1 the DNS server.  

`docker run --name dns-proxy-server  -p 5380:5380  -p 53:53/udp  -v /var/run/docker.sock:/var/run/docker.sock defreitas/dns-proxy-server `

Please consider adding this to the documentation.  Thanks!

**Comment by imjosh** [comment]
> Where  did you ran that command? In which terminal? 

From the Windows command prompt

> I am wondering about this section `/var/run/docker.sock:/var/run/docker.sock` it will work in Windows?

Yes, it works (somehow) and it's required for it to work.

> I tried to test it on Windows 10 but I had not success.

I'm not sure if it works for your intended purpose (primarily for dns within containers?).  But it does work for sure as a Windows DNS proxy.  

cheers

**Comment by mageddo** [comment]
I finally updated the docs about how to use on Windows, thanks for your contribution, if you notice any issue please let me know

regards.
