### ISSUE TITLE
DNS Resolution is very slow for container names -- >10 seconds

### ISSUE THREAD

**Issue by ak2766** [mageddo/dns-proxy-server#68]
I'm testing out your DNS Proxy Server but it appears to be very slow for docker container hostname resolution.  I can resolve Internet hostnames in an instant but container hostname resolution takes over 10 seconds before I start getting replies to my ping requests.

I'm on Ubuntu 16.04.4 LTS if that matters.

Let me know what I can provide to help track down the issue.

**Comment by mageddo** [comment]
@ak2766 Thanks for use DPS

You take 10 seconds in which scenario? by accessing the browser, by running a `ping` command, `nslookup`?

I never got any delay in DNS resolution from the browser or nslookup from terminal, but I notice some delay in ping command testing it right now, please confirm your test source, then we can investigate that.

Regards

**Comment by ak2766** [comment]
Hi Mageddo.

Yes, it happens when I'm sending pings (I did mention in the post above, maybe you missed it).

I've started the `dns-proxy-server` as follows:
```
docker run -h dns.mageddo --name dns-proxy-server -p 5380:5380 -v /var/run/docker.sock:/var/run/docker.sock -v /etc/resolv.conf:/etc/resolv.conf -d defreitas/dns-proxy-server
```
I then started a `CentOS` image with the hostname `pingclient.example.com` as follows:
```docker run -it --name pingclient -h pingclient.example.com -d centos```

I then created an image based on `CentOS` with `bind-utils` and `net-tools` and started it:
```docker run -it --name pinger -h pinger.example.com -d pinger```

I then pinged `pingclient` from the `pinger` with the following results:
```docker exec -i pinger ping -c4 pingclient.example.com
PING pingclient.example.com (172.17.0.3) 56(84) bytes of data.
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=1 ttl=64 time=0.043 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=2 ttl=64 time=0.062 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=3 ttl=64 time=0.096 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=4 ttl=64 time=0.102 ms

--- pingclient.example.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 12044ms
rtt min/avg/max/mdev = 0.043/0.075/0.102/0.026 ms
```

As you can see, it took 12.044s to send 4 ping most of which was spent waiting for DNS to resolve the name.

**Comment by ak2766** [comment]
Interestingly, `dig` returns results very quickly:
```
$ docker exec -i pinger dig pingclient.example.com

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> pingclient.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12692
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;pingclient.example.com.		IN	A

;; ANSWER SECTION:
pingclient.example.com.	0	IN	A	172.17.0.3

;; Query time: 0 msec
;; SERVER: 172.17.0.2#53(172.17.0.2)
;; WHEN: Sun May 13 02:08:12 UTC 2018
;; MSG SIZE  rcvd: 78
```
Yet, pinging immediately after still results in a long wait before ping replies start coming back:
```
$ docker exec -i pinger ping -c4 pingclient.example.com
PING pingclient.example.com (172.17.0.3) 56(84) bytes of data.
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=2 ttl=64 time=0.042 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=3 ttl=64 time=0.052 ms
64 bytes from 172.17.0.3 (172.17.0.3): icmp_seq=4 ttl=64 time=0.082 ms

--- pingclient.example.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 12043ms
rtt min/avg/max/mdev = 0.042/0.055/0.082/0.016 ms
```

**Comment by ak2766** [comment]
For completeness sake, when I ping the IP Address, response is immediate:
```
docker exec -i pinger ping -c4 172.17.0.3
PING 172.17.0.3 (172.17.0.3) 56(84) bytes of data.
64 bytes from 172.17.0.3: icmp_seq=1 ttl=64 time=0.058 ms
64 bytes from 172.17.0.3: icmp_seq=2 ttl=64 time=0.064 ms
64 bytes from 172.17.0.3: icmp_seq=3 ttl=64 time=0.127 ms
64 bytes from 172.17.0.3: icmp_seq=4 ttl=64 time=0.109 ms

--- 172.17.0.3 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3065ms
rtt min/avg/max/mdev = 0.058/0.089/0.127/0.030 ms
```

**Comment by ak2766** [comment]
FYI: I've just repeated the experiment with a user defined network and ping is now super responsive:

I created a user defined network as below:
`docker network create dockernet`

I then added `--network dockernet` option as I started the containers above.

This site was instrumental in my experimentation:
[User Defined Bridges](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge)

Cheers,
ak.

**Comment by ak2766** [comment]
Update:

It appears that the fast response is not always guaranteed.  Sometimes super fast other times I get that same ~10 second delay before I get my responses.

**Comment by mageddo** [comment]
@ak2766 I think I got it.

Basically when you ping a hostname it will do a second question to DNS server asking for reverse DNS lookup eg. `2.0.18.172.in-addr.arpa.`, as it doesn't exists, remote server returns an error code, DPS code was with a bug that returns nothing when it receives an error code from remote server then ping timeouts after 10s and keep going.

I will pre-release version **2.5.1** and keep testing.

Thank you very much for your contribution.

**Comment by mageddo** [comment]
[PR](https://github.com/mageddo/dns-proxy-server/pull/69)

**Comment by ak2766** [comment]
> Thank you very much for your contribution.

Thank you much more for creating a tool that makes my life really easy while getting to know Docker.

**Comment by ak2766** [comment]
I've been running this peridically (stopping and starting all containers prior to testing):

`for u in {1..1000}; do ping -f -c 100 pingclient.example.com 2>&1 | egrep transmitted; done`

I haven't seen a number > 2ms.

Solid fix muchly appreciated.
