### ISSUE TITLE
postfix could not resolve dns.

### ISSUE THREAD

**Issue by johnbritto1** [mageddo/dns-proxy-server#78]
On the first deployment, docker assigns a NAT IP, eg: 10.10.10.2 which is appended on /etc/resolv.conf
When we restart the dns-proxy-server, docker somethings assign different NAT IP, eg 10.10.10.3.
Postfix (In host) usually on restart, copy the /etc/resolv.conf to /var/spool/postfix/etc/resolv.conf
the value set in /var/spool/postfix/etc/resolv.conf is IP: 10.10.10.3.  

Hence, I have to restart postfix every time when the IP assigned to dns-proxy-server change.
Is there any way to automate this behaviour. 

Thanks.

**Comment by johnbritto1** [comment]
For some reason, I could not test by manually modifying the postfix resolve.conf (/var/spool/postfix/etc/resolv.conf). But surely I will test again and report back
But It looks like when postfix restart, it actually does copy the /etc/resolve.conf to /var/spool/postfix/etc/resolv.conf.
In past, I usually restart postfix and that solve the problem. 

I think having MG_RESOLVCONF env to support more than one resolv entry would be a solution.

**Comment by mageddo** [comment]
Okay, so let's wait your feedback then we can work on that

**Comment by johnbritto1** [comment]
Updating the /var/spool/postfix/etc/resolv.conf with the values of /etc/resolv.conf makes the postfix to function properly.

**Comment by mageddo** [comment]
MG_RESOLVCONF supports multiple conf files since DPS 3.5.0, [see the docs][1] . In your case run DPS  docker container with static IP is also an option.

Closing the issue as we already have a solution, thanks for your help.

[1]: http://mageddo.github.io/dns-proxy-server/latest/en/3-configuration/#environment-variable-configuration
