### ISSUE TITLE
CNAME Support

### ISSUE THREAD

**Issue by mageddo** [mageddo/dns-proxy-server#82]
It would be great if user would have the ability to create CNAME entries

**Comment by RichardBronosky** [comment]
Any updates on this?

**Comment by mageddo** [comment]
This feature wasn't developed yet, Do you need to create aliases to existing hostnames? Today you can achieve this by setting multiple hostnames on the `HOSTNAMES` env variable when starting your docker container

**Comment by mageddo** [comment]
Please checkout the [latest release](https://github.com/mageddo/dns-proxy-server/releases/tag/2.13.1) where the feature was developed
