### ISSUE TITLE
add container name

### ISSUE THREAD

**Issue by antarus** [mageddo/dns-proxy-server#86]
Hello, would it be possible to add the management of container names a bit like https://github.com/dvddarias/docker-hoster.

If I launch services via docker-compose, I would like to be able to access them with their name without having to add a configuration hostname.

thanks

**Comment by mageddo** [comment]
I think it makes sense. You mean solve by container name or docker-compose service name?

**Comment by antarus** [comment]
container name and docker-compose service name seem good :D

**Comment by mageddo** [comment]
Hello @antarus 

Feature was developed and it's [on this branch](https://github.com/mageddo/dns-proxy-server/blob/feature/86). The way to use it's [documented here](https://github.com/mageddo/dns-proxy-server/blob/feature/86/docs/features.md#access-container-by-its-container-name--service-name). 

**Points**
* `.docker` suffix was used by convention as every FQDN [must have an domain](https://en.wikipedia.org/wiki/Domain_name)
* Feature is disabled by default cause all previous versions haven't it, so will keep it disabled to make DPS in a standard behavior
* Feature can be activated by command line, json conf or environment variable as documented at the docs


Please tell me if you agree with the feature?

**Comment by mageddo** [comment]
Checkout the pull request #88

**Comment by mageddo** [comment]
New version was released https://github.com/mageddo/dns-proxy-server/releases/tag/2.7.0

**Comment by antarus** [comment]
perfect thanks
