### ISSUE TITLE
could you have an armhf image?

### ISSUE THREAD

**Issue by gbrault** [mageddo/dns-proxy-server#87]
docker load the image on armf but refuse executing: this is because the image is not compiled for armf...

**Comment by mageddo** [comment]
Hi @gbrault, can you elaborate what is armf? I searched on Google but didn't found concrete results. You mean generate a binary release for arm processors?

**Comment by mageddo** [comment]
I found [this docker user ](https://hub.docker.com/r/arm64v8). Are you talking about generate a DPS docker image based on images of that user repository like https://hub.docker.com/r/arm64v8/debian/ ?

**Comment by mageddo** [comment]
If yes, which arm are you interested in? Is this image ok for you ? https://hub.docker.com/r/arm64v8/debian/

**Comment by gbrault** [comment]
Thanks @mageddo, I elaborate:
1- I have to investigate the reference you provided
2- The reference image for me for ARM is Debian based raspberry pi aka raspbian https://www.raspberrypi.org/downloads/raspbian/
3- I misspelled armf actually it's armhf (armhf stands for "arm hard float", and is the name given to a debian port for arm processors (armv7+) that have hardware floating point support), Anyway Raspbian is the target (you will have to figure out: maybe they are 32 bits and 64 bits flavor). My target processor is Raspberry pi 3 (which is 64 bits?) ( uname -a => Linux raspberrypi 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux )

**Comment by mageddo** [comment]
Okay, I compiled arm and arm64 images, you could try to run them

[dns-proxy-server-linux-arm-2.7.0.tgz](https://github.com/mageddo/dns-proxy-server/releases/download/2.7.0/dns-proxy-server-linux-arm-2.7.0.tgz)
[dns-proxy-server-linux-arm64-2.7.0.tgz](https://github.com/mageddo/dns-proxy-server/releases/download/2.7.0/dns-proxy-server-linux-arm64-2.7.0.tgz)

If you need the docker docker image 

* Clone this branch
* Download `dns-proxy-server-linux-arm-2.7.0.tgz` and `dns-proxy-server-linux-arm64-2.7.0.tgz` then move them on `/build` directory (create this if necessary)
* Build docker image using

```bash
$ docker-compose build prod-build-arm7x86-image-dps
$ docker-compose build prod-build-arm8x86-image-dps
$ docker-compose build prod-build-arm8x64-image-dps
```

**Comment by gbrault** [comment]
Thanks: I give a try and let you know!

**Comment by gbrault** [comment]
I am not successful building the docker image (32 bits).
1- cloned https://github.com/mageddo/dns-proxy-server/tree/feature/87
2- created build directory
3- copied both file in build
4- docker-compose build prod-build-arm7x86-image-dps

did that on a windows10 machine

tells me

C:\Users\gbrau\dns-proxy-server>docker-compose build prod-build-arm7x86-image-dps
WARNING: The PWD variable is not set. Defaulting to a blank string.
WARNING: The TRAVIS_BRANCH variable is not set. Defaulting to a blank string.
WARNING: The REPO_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The HOME variable is not set. Defaulting to a blank string.
ERROR: No such service: prod-build-arm7x86-image-dps

Any idea?

**Comment by mageddo** [comment]
Look likes `prod-build-arm7x86-image-dps` it's no present on docker-compose.yml, but it is for me. Make sure [this is our last commit](https://github.com/mageddo/dns-proxy-server/commit/b714a857f46afe69e5889b6b4b8d3192eff99506), try 

```
$ git checkout feature/87
```
or 
```
git checkout b714a857f46afe69e5889b6b4b8d3192eff99506
```

Then try it again

**Comment by mageddo** [comment]
Also make sure you are running docker-compose on folder that have that content
```
.
├── build
├── builder
├── cache
├── conf
├── controller
├── countlines
├── dns.go
├── docker-compose.yml
├── Dockerfile
├── Dockerfile.arm7x86
├── Dockerfile.arm8x64
├── Dockerfile.arm8x86
├── Dockerfile.hub
├── docs
├── events
├── files
├── flags
├── LICENSE
├── log
├── proxy
├── README.md
├── RELEASE-NOTES.md
├── resolvconf
├── service
├── static
├── test
├── utils
├── vendor
├── VERSION
```

**Comment by gbrault** [comment]
Ok, the container is now in my Docker HUB
you can see https://hub.docker.com/r/gbrault/dns-proxy-server-arm7x86/
I have it alive in my RPI up and running!
I need now to test it!
I let you know the result

**Comment by gbrault** [comment]
Most of it works, but I have an issue when not providing --hostnames creating containers: it seems you then use the container ID as the default name. Here is an excerpt of the logs


2018/10/13 09:07:53 INFO f=docker.go:60 pkg=github.com/mageddo/dns-proxy-server/events/docker m=HandleDockerEvents status=container-from-list-begin, container=/nextcloud
2018/10/13 09:07:53 INFO f=local.go:34 pkg=github.com/mageddo/dns-proxy-server/events/local m=LoadConfiguration status=begin, confPath=/app/conf/config.json
2018/10/13 09:07:53 INFO f=local.go:37 pkg=github.com/mageddo/dns-proxy-server/events/local m=LoadConfiguration  status=openingFile
2018/10/13 09:07:53 INFO f=local.go:65 pkg=github.com/mageddo/dns-proxy-server/events/local m=LoadConfiguration  status=success
2018/10/13 09:07:53 DEBUG f=docker.go:173 pkg=github.com/mageddo/dns-proxy-server/events/docker m=putHostnames container=/nextcloud, network=myNetwork, ip=172.18.0.4
2018/10/13 09:07:53 DEBUG f=docker.go:185 pkg=github.com/mageddo/dns-proxy-server/events/docker m=putHostnames host=5b77a6c81d52, ip=172.18.0.4
2018/10/13 09:07:53 INFO f=docker.go:66 pkg=github.com/mageddo/dns-proxy-server/events/docker m=HandleDockerEvents status=container-from-list-success, container=/nextcloud, hostnames=[5b77a6c81d52]

So I have a question: when hostnames is not specified what is the default?

Locking to docker documentation => please see
 [Container networking](https://docs.docker.com/config/containers/container-networking/#published-ports)

Attached complete log
[log.txt](https://github.com/mageddo/dns-proxy-server/files/2475298/log.txt)

**Comment by gbrault** [comment]
I have found the issue: portainer, the deployment tool I use is setting this hostname...
So: no need for investigation!

Thx, I keep you posted

**Comment by mageddo** [comment]
> So I have a question: when hostnames is not specified what is the default?

DPS uses `HOSTNAMES` env and/or `--hostnames` option. I'm not sure but reading the link you posted and based on my past experiences, docker will put the container name at hostname option then DPS will use that..

DPS has a new feature when you can set container name / service name as hostname, but it is disabled by default [see the reference](http://mageddo.github.io/dns-proxy-server/docs/features#access-container-by-its-container-name--service-name)

**Comment by mageddo** [comment]
Glad it works for you, so next step is to officially generate ARM images, I think it would be great to document how compile DPS for others platforms too.

**Comment by mageddo** [comment]
I'm just curious, What is the objective to you run docker inside a RPI with portainer, DPS, etc. ?

**Comment by hgross** [comment]
> Glad it works for you, so next step is to officially generate ARM images, I think it would be great to document how compile DPS for others platforms too.

Indeed - any news/plans on the officially generated ARM images?

**Comment by mageddo** [comment]
@hgross I already did some code but didn't complete, I'm working on this now and  I plan arm support to be released on the next DPS version, not sure when cause I code on my free time.

**Comment by mageddo** [comment]
Version [2.10.3](https://github.com/mageddo/dns-proxy-server/releases/tag/2.10.3) were just released supporting ARM arch, [here instructions](https://github.com/mageddo/dns-proxy-server/blob/master/docs/developing/Compiling-the-project-from-source.md#building-binary-for-specific-arch) of how build your specific arch manually.

Can someone give it a test and check if ARM images works?

**Comment by mageddo** [comment]
DPS is builting arm docker images as well, take a look at docker hub

**Comment by hgross** [comment]
Awesome, just tested it on a Raspberry Pi 3 B+ and it works as expected. 
Regarding Gradle - I can only recommend it. 
We use it a lot (also with docker, check out https://github.com/palantir/gradle-docker) and are happy with it.

**Comment by mageddo** [comment]
Ok, I'll mark it as done. If you have some issue feel free to start a talk
