### ISSUE TITLE
Support for Wildcard DNS in multilevel

### ISSUE THREAD

**Issue by rayout** [mageddo/dns-proxy-server#91]
Wildcard works, but only for one level.
If i set hostname ".localhost" it resolve "test.localhost" and do not resolve "test2.test.localhost".
I think it should work for.

**Comment by mageddo** [comment]
I think it should work too

**Comment by mageddo** [comment]
I just released https://github.com/mageddo/dns-proxy-server/releases/tag/2.9.1 please take a look

**Comment by rayout** [comment]
All works! Thank you!
